name: Release docker image
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check Docker Registory
        id: check-docker-registory
        run: |
          release_version=$(cat .simplesamlphp_version)
          echo "Release version is ${release_version}"
          if [[ "$( curl -sfL https://registry.hub.docker.com/v2/repositories/kenchan0130/simplesamlphp/tags | jq --arg version "${release_version}" '.results[] | select(.name == $version)' )" ]]; then
            echo "${release_version} is already released."
            echo "::set-output name=release::none"
          else
            echo "::set-output name=release::required"
          fi
      - name: Build and Push
        if: ${{ steps.check-docker-registory.outputs.release == 'required' }}
        env:
          REGISTRY_HOST: index.docker.io
          DOCKERHUB_USERNAME: kenchan0130
        run: |
          make build
          echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
          make push
      - name: Sync Docker Hub Description
        if: ${{ steps.check-docker-registory.outputs.release == 'required' }}
        uses: peter-evans/dockerhub-description@v2.4.3
        env:
          DOCKERHUB_USERNAME: kenchan0130
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: kenchan0130/simplesamlphp
