name: Release docker image
on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
      - uses: actions/checkout@v2
      - name: Build and Push
        env:
          REGISTRY_HOST: index.docker.io
          DOCKERHUB_USERNAME: kenchan0130
        run: |
          make build
          echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
          make push
      - name: Sync Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.1.0
        env:
          DOCKERHUB_USERNAME: kenchan0130
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: kenchan0130/simplesamlphp
