name: Create Pull Request of SimpleSAMLphp new version
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  PULL_REQUEST_BRANCH_PREFIX: create-pull-request/simplesamlphp-

jobs:
  check-latest-version:
    runs-on: ubuntu-latest
    outputs:
      is-continued-pr: ${{ steps.check-latest-version.outputs.update == 'required' && steps.check-pull-request.outputs.pr == 'required' }}

    steps:
      - uses: actions/checkout@v2
      - name: Check latest version
        id: check-latest-version
        run: |
          latest_info=$( curl -sfL https://api.github.com/repos/simplesamlphp/simplesamlphp/releases/latest )
          latest_version=$( echo "${latest_info}" | jq -r .tag_name | tr -d 'v' )
          echo "::set-output name=latest-version::${latest_version}"
          if [[ "$( cat .simplesamlphp_version | tr -d '.' )" -lt "$( echo "${latest_version}" | tr -d '.' )" ]]; then
            echo "::set-output name=update::required"
          else
            echo "${latest_version} may be already exist."
            echo "::set-output name=update::none"
          fi
      - name: Check current pull request
        id: check-pull-request
        run: |
          branch_name="${{ env.PULL_REQUEST_BRANCH_PREFIX }}${{ steps.check-latest-version.outputs.latest-version }}"
          if [[ "$( git ls-remote --heads "$( git config --get remote.origin.url )" "${branch_name}" )" ]]; then
            echo "${branch_name} branch is already exist."
            echo "::set-output name=pr::none"
          else
            echo "::set-output name=pr::required"
          fi

  create-pull-request:
    needs: check-latest-version
    runs-on: ubuntu-latest
    if: needs.check-latest-version.outputs.is-continued-pr == true
    steps:
      - uses: actions/checkout@v2
      - name: Detect latest version
        id: detect-latest-version
        run: |
          latest_info=$( curl -sfL https://api.github.com/repos/simplesamlphp/simplesamlphp/releases/latest )
          latest_version=$( echo "${latest_info}" | jq -r .tag_name | tr -d 'v' )
          echo "${latest_version}" > .simplesamlphp_version
          echo "::set-output name=latest-version::${latest_version}"
          echo "::set-output name=release-url::$( echo "${latest_info}" | jq -r .html_url)"
      - name: Git status
        run: |
          git status
      - name: Git diff
        run: |
          git diff
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        id: create-pull-request
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Bump simplesamlphp version to ${{ steps.dlv.outputs.latest-version }}
          body: |
            This is an automated PR to update the [simplesamlphp](https://github.com/simplesamlphp/simplesamlphp).

            - Check if there is any omission between [${{ steps.detect-latest-version.outputs.latest-version }}](${{ steps.detect-latest-version.outputs.release-url }}) and the existing version.
            - This is auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
          branch: ${{ env.PULL_REQUEST_BRANCH_PREFIX }}${{ steps.detect-latest-version.outputs.latest-version }}
          base: master
          labels: automated pr
      - name: Check outputs
        run: |
          echo "Created a pull request - ${{ steps.create-pull-request.outputs.pull-request-url }}"
