name: Create Pull Request of SimpleSAMLphp new version
on:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  check_latest_version:
    runs-on: ubuntu-latest
    outputs:
      continue_pr: ${{ steps.clv.outputs.continue_pr }}

    steps:
      - uses: actions/checkout@v2
      - name: Check latest version
        id: clv
        run: |
          latest_info=$(curl -sfL https://api.github.com/repos/simplesamlphp/simplesamlphp/releases/latest)
          latest_version=$(echo "${latest_info}" | jq .tag_name | tr -d 'v')
          if [[ "$(cat .simplesamlphp_version | tr -d '.')" -lt "$(echo "${latest_version}" | tr -d '.')" ]]; then
            echo "::set-output name=continue_pr::true"
          else
            echo "${latest_version} may be already exist."
            echo "::set-output name=continue_pr::false"
          fi

  create_pull_request:
    name: Create pull request
    needs: check_latest_version
    runs-on: ubuntu-latest
    if: ${{ needs.check_latest_version.outputs.continue_pr }}

    steps:
      - uses: actions/checkout@v2
      - name: Detect latest version
        id: dlv
        run: |
          latest_info=$(curl -sfL https://api.github.com/repos/simplesamlphp/simplesamlphp/releases/latest)
          latest_version=$(echo "${latest_info}" | jq .tag_name | tr -d 'v')
          echo "${latest_version}" > .simplesamlphp_version
          echo "::set-output name=new_version::${latest_version}"
          echo "::set-output name=release_url::$(echo "${latest_info}" | jq .url)"
      - name: Create a temporary tag branch
        run: |
          git config --global user.name 'GitHub'
          git config --global user.email 'noreply@github.com'
          git checkout -b temp-${GITHUB_REF:10}
          git push --set-upstream origin temp-${GITHUB_REF:10}
      - name: Git status
        run: |
          git status
      - name: Git diff
        run: |
          git diff
      - name: Git branch
        run: |
          git branch
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        id: cpr
        with:
          title: Bump simplesamlphp version to ${{ steps.dlv.outputs.latest_version }}
          body: |
            This is an automated PR to update the [simplesamlphp](https://github.com/simplesamlphp/simplesamlphp).

            - Check if there is any omission between [${{ steps.dlv.outputs.latest_version }}](${{ steps.dlv.outputs.release_url }}) and the existing version.
            - This is auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
          branch: master
          branch-suffix: short-commit-hash
          labels: automated pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
      - name: Delete tag branch
        run: |
          git push --delete origin temp-${GITHUB_REF:10}
